### ISSUE TITLE
Build UI and style for details panel (basic first version)

### ISSUE THREAD

**Issue by sahilshahpatel** [Bone008/orbiteye#20]
This is ONLY the visual part, not the logic behind it. Feel free to use hard-coded values without any React logic.

- [x] Figure out where it should be placed on the page.
- [x] Make it possible to show/hide the panel (preferably based on a React prop input to the component).
- [x] Show name of satellite.
- [x] Show dummy launch date.
- [x] Show operational status & decay date if applicable.

**Comment by avelinpv** [comment]
I have added a component for the whole panel on the right side that contains both the filter panel and the detail panel. The detail panel will only be visable when a satelite is selected, and currently only uses **fake data**. It will have to be hooked to the selecting of satelite in the other components that is in the view selection (will leave that to issue #46 to fix togheter with the logic). 

Also: maybe will have to fix so the detail view is not visable when in the view selection since no satelite is selected in that mode. And that it clears the selecting when changing mode to views without satelite (i.e. origin/decay?)

Let me know if you have any feedback on the changes and the styling. Will leave this issue open for now if more changes is needed.

**Comment by Bone008** [comment]
New TODO:

- [x] add all the fields that are also visible in the filter
- [x] improve styling to make it more legible and optimize vertical space it takes up (e.g. make the toggle button very small in the corner)
- [x] add "external link" icon to link to NASA
- [x] rename COSPAR ID to "International Designator" or similar
- [x] fix line wrapping of the "i" icon in the "Orbit types" line (probably make it wider?)
- [x] make "i" icon pop out more somehow
