### ISSUE TITLE
Build UI and style for timeline component

### ISSUE THREAD

**Issue by Bone008** [Bone008/orbiteye#41]
(This is only about the visual part, NOT the logic behind it about hooking it up to the filter etc.)

The timeline must have:

- [x] a bar showing years at regular intervals based on placeholder values "minYear" and "maxYear"
- [x] a handle with 2 endpoints that are individually draggable
- [ ] nice to have: when clicking and dragging the middle of the handle, it should move both start & end points simultaneously

**Comment by avelinpv** [comment]
Current timeline has hardcoded values for the marks (the bottom numbers). It also has hard coded min/max values that sets the range of the slider, this should be based on the dataset. Couldn't make it work because of the max-value being undefind when starting the render of the slider. This also sets the initial value of the two thumbs to the lowest, but one should be set on min and the other on max or something else. Haven't found a way to solve that. 

Can be continued now with the logig in #42 I think. 

Let me know if there are stuff that isn't working or any thought on the styling.

**Comment by Bone008** [comment]
Seems to be fully functional now
