### ISSUE TITLE
Create informational help

### ISSUE THREAD

**Issue by sahilshahpatel** [Bone008/orbiteye#65]
The unique factor of our application is that is is supposed to be educational. We need to design this interaction and write up the explanations.

- [x] Design the interaction (ideas include fullscreen-ish modals/popups, small hover windows, etc)
- [x] Create writeups:
     - [x] For all orbit types (not including subtypes for now)
     - [x] For each mode (design the cards of the landing page)
- [x] Restyle filter panel to make info button look nice

**Comment by avelinpv** [comment]
Informational images created: [GoogleDrive](https://drive.google.com/drive/folders/1-5hdfkYuOUKvpxdkCF-tWgGhd0_b8npn?usp=sharing)

All png files for transparent backgrounds

**Comment by sahilshahpatel** [comment]
Screenshot of my current version of the mode description images (**I haven't updated the text yet!**)
![image](https://user-images.githubusercontent.com/30131974/156926024-b5ed5625-af6f-4f75-ba9b-cbe53894e757.png)

**Comment by sahilshahpatel** [comment]
@avelinpv I noticed you made an image for Orbits 2D -- that's not going to be a permanent resident in this UI though! Now that Lukas has created the switch with in the view in #52 there isn't a need for it.

Originally, that fourth option was going to be "Launch", but I wouldn't waste time making an image for that when we don't really know what we want it to be/if we'll have time to make it yet.

What I wanted to ask is this: Should we keep the orbits image as is? Or should we combine the "2D" and "3D" images somehow to represent that both views are available that way?

**Comment by avelinpv** [comment]
So I did the 2D iage since I had the background done and it was simple to just add the lines on top and I wasn't sure how we would decide to do with the 4 boxes in the view selector. Now I see that we have cut two out and only have orbits and orgin which looks good. But one idea I had before was to merge the images, i.e. like below.
![notNIceModeImage](https://user-images.githubusercontent.com/30972483/156934158-46e9f27a-68d0-42a6-ae37-461246d224e5.png)
I don't really like the merge image at all after trying it out, but if you guys would like that then there is an option. Or if we want to use it in any other way we could do that too since the image exist. 

Also, I don't think its a good idea to do the launch image before having a clear picture of what it would be since it takes a bit of time to do the images. So I didn't intend to do it before we talked about it again either way :)

**Comment by avelinpv** [comment]
@sahilshahpatel I noticed when tryig out the information panel that somehow the view selector image is visible and seeps through the globe of the image in the panel. In the image below, the orgin image seeps through the globe image and is most visable in the blue/green part of the globe. The view selector is also clickable even when the information panel is activated, so I am able to click through the info panel. 
![image](https://user-images.githubusercontent.com/30972483/156934646-84ab560e-4028-4dd9-82b2-b09858a59168.png)
However, when I go into a mode, the background is now not visable at all through the green/blue part of the globe. I don't know if that is intentional, so just a head up if you haven't noticed it.

**Comment by sahilshahpatel** [comment]
Hmm... yeah the split image doesn't look great as is... I wonder if you put an actual line dividing them if that would make it more clear, but then it gets really busy too...

If we do use that in the end, I also think you'd just want continent outlines instead of countries to make it less busy. But I'm assuming that's more work for you so it's probably not worth the effort, at least for now.

**Comment by avelinpv** [comment]
I tried it out with the contintent outlines only and it still looks not so good. Same problem still that it looks to crowded in the image and the cut between the images is wierd. Might look into it more later, but for now we can keep the image for the 3d mode in the selector.
